

package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;
	
	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}

init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}

terminal PROG, LBRACE, RBRACE, CONST, ASSIGN, SEMI, COMMA, OR, UNION;
terminal LBRACKET, RBRACKET, STATIC, LPAREN, RPAREN, VOID, COLON, IF, ELSE, BREAK, CONTINUE, RETURN;
terminal READ, PRINT, INCREMENT, DECREMENT, AND, PLUS, MINUS, NEW, DOT, ASTERISK, FORWARD_SLASH, PERCENT;
terminal EQUAL, NOT_EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL;
terminal Integer NUMBER;
terminal String IDENT;
terminal Character CHAR;
terminal Boolean BOOL;

nonterminal VarOrConstDeclList VarOrConstDeclList;
nonterminal VarOrConstDecl VarOrConstDecl;
nonterminal VarDecl VarDecl;
nonterminal VarDeclList VarDeclList;
nonterminal StatementList StatementList;
nonterminal Statement Statement;
nonterminal DesignatorStatement DesignatorStatement;
nonterminal Condition Condition;
nonterminal Assignop Assignop;
nonterminal ActPars ActPars;
nonterminal CondTerm CondTerm;
nonterminal Relop Relop;
nonterminal Addop Addop;
nonterminal Setop Setop;
nonterminal Mulop Mulop;

nonterminal rs.etf.pp1.symboltable.concepts.Obj ProgName, Program, MethodDecl, MethodTypeName, DesignName, VarDeclElems, ConstDeclSuffix, ConstDecl;
nonterminal rs.etf.pp1.symboltable.concepts.Struct CondFact, Type, Term, Factor, Expr, Designator;

Program ::= (Program) PROG ProgName:progName VarOrConstDeclList:V1 LBRACE MethodDecl:M2 RBRACE {: RESULT=new Program(progName, V1, M2); RESULT.setLine(progNameleft); :};

ProgName ::= (ProgName) IDENT:progName {: RESULT=new ProgName(progName); RESULT.setLine(progNameleft); :};

VarOrConstDecl ::= (VarOrConstDeclVar) VarDecl:V1 {: RESULT=new VarOrConstDeclVar(V1); RESULT.setLine(V1left); :}
				| (VarOrConstDeclConst) ConstDecl:C1 {: RESULT=new VarOrConstDeclConst(C1); RESULT.setLine(C1left); :}
				;

VarOrConstDeclList ::= (VarOrConstDeclList1) VarOrConstDeclList:V1 VarOrConstDecl:V2 {: RESULT=new VarOrConstDeclList1(V1, V2); RESULT.setLine(V1left); :}
					| (NoVarOrConstDeclList) {: RESULT=new NoVarOrConstDeclList(); :} /* epsilon */
					;

ConstDecl ::= (ConstDecl) CONST Type:T1 ConstDeclSuffix:C2 SEMI {: RESULT=new ConstDecl(T1, C2); RESULT.setLine(T1left); :};

ConstDeclSuffix ::= (ConstDeclSuffixNum1) ConstDeclSuffix:C1 COMMA IDENT:constName ASSIGN NUMBER:literal {: RESULT=new ConstDeclSuffixNum1(C1, constName, literal); RESULT.setLine(C1left); :}
				| (ConstDeclSuffixNum2) IDENT:constName ASSIGN NUMBER:literal {: RESULT=new ConstDeclSuffixNum2(constName, literal); RESULT.setLine(constNameleft); :}
				| (ConstDeclSuffixChar1) ConstDeclSuffix:C1 COMMA IDENT:constName ASSIGN CHAR:ch {: RESULT=new ConstDeclSuffixChar1(C1, constName, ch); RESULT.setLine(C1left); :}
				| (ConstDeclSuffixChar2) IDENT:constName ASSIGN CHAR:ch {: RESULT=new ConstDeclSuffixChar2(constName, ch); RESULT.setLine(constNameleft); :}
				| (ConstDeclSuffixBool1) ConstDeclSuffix:C1 COMMA IDENT:constName ASSIGN BOOL:bo {: RESULT=new ConstDeclSuffixBool1(C1, constName, bo); RESULT.setLine(C1left); :}
				| (ConstDeclSuffixBool2) IDENT:constName ASSIGN BOOL:bo {: RESULT=new ConstDeclSuffixBool2(constName, bo); RESULT.setLine(constNameleft); :}
				;
		
VarDeclList ::= (VarDeclList1) VarDeclList:V1 VarDecl:V2 {: RESULT=new VarDeclList1(V1, V2); RESULT.setLine(V1left); :}
			| (NoVarDeclList) {: RESULT=new NoVarDeclList(); :} /* epsilon */
			;

VarDecl ::= (VarDecl1) Type:T1 VarDeclElems:V2 SEMI {: RESULT=new VarDecl1(T1, V2); RESULT.setLine(T1left); :}
		| (VarDeclErrorComma) error:l COMMA {: parser.report_error("Izvrsen oporavak pri deklaraciji promjenjivih do , u liniji " + lleft, null); :} {: RESULT=new VarDeclErrorComma(); :}
		| (VarDeclErrorSemi) error:l SEMI {: parser.report_error("Izvrsen oporavak pri deklaraciji promjenjivih do ; u liniji " + lleft, null); :} {: RESULT=new VarDeclErrorSemi(); :}
		;
			
VarDeclElems ::= (VarDeclElems1Multiple) VarDeclElems:V1 COMMA IDENT:varName {: RESULT=new VarDeclElems1Multiple(V1, varName); RESULT.setLine(V1left); :}
		| (VarDeclElemsArrayMultiple) VarDeclElems:V1 COMMA IDENT:varName LBRACKET RBRACKET {: RESULT=new VarDeclElemsArrayMultiple(V1, varName); RESULT.setLine(V1left); :}
		| (VarDeclElems1) IDENT:varName {: RESULT=new VarDeclElems1(varName); RESULT.setLine(varNameleft); :}
		| (VarDeclElemsArray) IDENT:varName LBRACKET RBRACKET {: RESULT=new VarDeclElemsArray(varName); RESULT.setLine(varNameleft); :}
		;


MethodDecl ::= (MethodDecl) MethodTypeName:M1 LPAREN RPAREN VarDeclList:V2 LBRACE StatementList:S3 RBRACE {: RESULT=new MethodDecl(M1, V2, S3); RESULT.setLine(M1left); :};

MethodTypeName ::= (MethodTypeNameVoid) VOID IDENT:methName {: RESULT=new MethodTypeNameVoid(methName); RESULT.setLine(methNameleft); :};



Type ::= (Type) IDENT:typeName {: RESULT=new Type(typeName); RESULT.setLine(typeNameleft); :};

Statement ::= (Statement1) DesignatorStatement:D1 SEMI {: RESULT=new Statement1(D1); RESULT.setLine(D1left); :}
			| (StatementReturn) RETURN SEMI {: RESULT=new StatementReturn(); :}
			| (StatementRead) READ LPAREN Designator:D1 RPAREN SEMI {: RESULT=new StatementRead(D1); RESULT.setLine(D1left); :}
			| (StatementPrintExpr) PRINT LPAREN Expr:E1 RPAREN SEMI {: RESULT=new StatementPrintExpr(E1); RESULT.setLine(E1left); :}
			| (StatementPrintExprWithNum) PRINT LPAREN Expr:E1 COMMA NUMBER:num RPAREN SEMI {: RESULT=new StatementPrintExprWithNum(E1, num); RESULT.setLine(E1left); :}
			;

StatementList ::= (StatementList1) StatementList:S1 Statement:S2 {: RESULT=new StatementList1(S1, S2); RESULT.setLine(S1left); :}
				| (NoStatementList) {: RESULT=new NoStatementList(); :} /* epsilon */
				;

DesignatorStatement ::= (DesignatorStatement1) Designator:D1 Assignop:A2 Expr:E3 {: RESULT=new DesignatorStatement1(D1, A2, E3); RESULT.setLine(D1left); :}
					| (DesignatorStatement2) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new DesignatorStatement2(D1, A2); RESULT.setLine(D1left); :}
					| (DesignatorStatementInc) Designator:D1 INCREMENT {: RESULT=new DesignatorStatementInc(D1); RESULT.setLine(D1left); :}
					| (DesignatorStatementDec) Designator:D1 DECREMENT {: RESULT=new DesignatorStatementDec(D1); RESULT.setLine(D1left); :}
					| (DesignatorStatement3) Designator:d1 Assignop:A1 Designator:d2 Setop:S2 Designator:d3 {: RESULT=new DesignatorStatement3(d1, A1, d2, S2, d3); RESULT.setLine(d1left); :}
					| (DesignatorStatementError) error:l SEMI
						{: parser.report_error("Izvrsen oporavak pri designator statement-u do ; u liniji " + lleft, null); :} {: RESULT=new DesignatorStatementError(); :}
					;

ActPars ::= (ActPars1) Expr:E1 {: RESULT=new ActPars1(E1); RESULT.setLine(E1left); :}
		| (ActPars2) ActPars:A1 COMMA Expr:E2 {: RESULT=new ActPars2(A1, E2); RESULT.setLine(A1left); :}
		| (NoActPars) {: RESULT=new NoActPars(); :} /* epsilon */
		;


Condition ::= (Condition1) CondTerm:C1 {: RESULT=new Condition1(C1); RESULT.setLine(C1left); :}
			| (Condition2) Condition:C1 OR CondTerm:C2 {: RESULT=new Condition2(C1, C2); RESULT.setLine(C1left); :}
			;


CondTerm ::= (CondTerm1) CondFact:C1 {: RESULT=new CondTerm1(C1); RESULT.setLine(C1left); :}
			| (CondTerm2) CondTerm:C1 AND CondFact:C2 {: RESULT=new CondTerm2(C1, C2); RESULT.setLine(C1left); :}
			;


CondFact ::= (CondFact1) Expr:E1 {: RESULT=new CondFact1(E1); RESULT.setLine(E1left); :}
			| (CondFact2) Expr:E1 Relop:R2 Expr:E3 {: RESULT=new CondFact2(E1, R2, E3); RESULT.setLine(E1left); :}
			;


Expr ::= (ExprPlus) Term:T1 {: RESULT=new ExprPlus(T1); RESULT.setLine(T1left); :}
		| (ExprMinus) MINUS Term:T1 {: RESULT=new ExprMinus(T1); RESULT.setLine(T1left); :}
		| (ExprMultiple) Expr:E1 Addop:A2 Term:T3 {: RESULT=new ExprMultiple(E1, A2, T3); RESULT.setLine(E1left); :}
		;

Term ::= (Term1) Factor:F1 {: RESULT=new Term1(F1); RESULT.setLine(F1left); :}
		| (Term2) Term:T1 Mulop:M2 Factor:F3 {: RESULT=new Term2(T1, M2, F3); RESULT.setLine(T1left); :}
		;


Factor ::= (Factor1) Designator:D1 {: RESULT=new Factor1(D1); RESULT.setLine(D1left); :}
		| (Factor2) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new Factor2(D1, A2); RESULT.setLine(D1left); :}
		| (FactorNum) NUMBER:N1 {: RESULT=new FactorNum(N1); RESULT.setLine(N1left); :}
		| (FactorChar) CHAR:C1 {: RESULT=new FactorChar(C1); RESULT.setLine(C1left); :}
		| (FactorBool) BOOL:B1 {: RESULT=new FactorBool(B1); RESULT.setLine(B1left); :}
		| (Factor3) NEW Type:T1 LBRACKET Expr:E2 RBRACKET {: RESULT=new Factor3(T1, E2); RESULT.setLine(T1left); :}
		| (Factor5) NEW Type:T1 LPAREN ActPars:A2 RPAREN {: RESULT=new Factor5(T1, A2); RESULT.setLine(T1left); :}
		| (Factor6) LPAREN Expr:E1 RPAREN {: RESULT=new Factor6(E1); RESULT.setLine(E1left); :}
		;
		

Designator ::= (Designator1) DesignName:dn {: RESULT=new Designator1(dn); RESULT.setLine(dnleft); :}
			| (DesignatorArray) DesignName:dn LBRACKET Expr:E1 RBRACKET {: RESULT=new DesignatorArray(dn, E1); RESULT.setLine(dnleft); :}
            ;
DesignName ::= (DesignName) IDENT:name {: RESULT=new DesignName(name); RESULT.setLine(nameleft); :};



Assignop ::= (Assignop) ASSIGN {: RESULT=new Assignop(); :};

Relop ::= (Equalop) EQUAL {: RESULT=new Equalop(); :}
		| (NotEqualop) NOT_EQUAL {: RESULT=new NotEqualop(); :}
		| (GreaterThanop) GREATER_THAN {: RESULT=new GreaterThanop(); :}
		| (GreaterThanOrEqualop) GREATER_THAN_OR_EQUAL {: RESULT=new GreaterThanOrEqualop(); :}
		| (LessThanop) LESS_THAN {: RESULT=new LessThanop(); :}
		| (LessThanOrEqualop) LESS_THAN_OR_EQUAL {: RESULT=new LessThanOrEqualop(); :}
		;

Addop ::= (AddopPlus) PLUS {: RESULT=new AddopPlus(); :}
		| (Subop) MINUS {: RESULT=new Subop(); :}
		;
		
Mulop ::= (Mulop1) ASTERISK {: RESULT=new Mulop1(); :}
		| (Divop) FORWARD_SLASH {: RESULT=new Divop(); :}
		| (Modop) PERCENT {: RESULT=new Modop(); :}
		;
		
Setop ::= (Setop1) UNION {: RESULT=new Setop1(); :};

