
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Sep 15 15:01:41 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 10;
  public static final int INCREMENT = 24;
  public static final int CHAR = 42;
  public static final int CONST = 5;
  public static final int ASTERISK = 31;
  public static final int LESS_THAN_OR_EQUAL = 39;
  public static final int NOT_EQUAL = 35;
  public static final int LPAREN = 13;
  public static final int SEMI = 7;
  public static final int CONTINUE = 20;
  public static final int MINUS = 28;
  public static final int DECREMENT = 25;
  public static final int GREATER_THAN = 36;
  public static final int STATIC = 12;
  public static final int RPAREN = 14;
  public static final int AND = 26;
  public static final int OR = 9;
  public static final int BOOL = 43;
  public static final int COMMA = 8;
  public static final int PLUS = 27;
  public static final int ASSIGN = 6;
  public static final int IF = 17;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 34;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int PERCENT = 33;
  public static final int NUMBER = 40;
  public static final int IDENT = 41;
  public static final int BREAK = 19;
  public static final int VOID = 15;
  public static final int COLON = 16;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int READ = 22;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int GREATER_THAN_OR_EQUAL = 37;
  public static final int FORWARD_SLASH = 32;
  public static final int LESS_THAN = 38;
  public static final int PRINT = 23;
}

