
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 13 12:38:35 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 11;
  public static final int INCREMENT = 25;
  public static final int CHAR = 43;
  public static final int CONST = 5;
  public static final int ASTERISK = 32;
  public static final int LESS_THAN_OR_EQUAL = 40;
  public static final int NOT_EQUAL = 36;
  public static final int LPAREN = 14;
  public static final int SEMI = 7;
  public static final int CONTINUE = 21;
  public static final int MINUS = 29;
  public static final int DECREMENT = 26;
  public static final int GREATER_THAN = 37;
  public static final int STATIC = 13;
  public static final int RPAREN = 15;
  public static final int AND = 27;
  public static final int OR = 9;
  public static final int BOOL = 44;
  public static final int COMMA = 8;
  public static final int PLUS = 28;
  public static final int ASSIGN = 6;
  public static final int IF = 18;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int EQUAL = 35;
  public static final int RBRACKET = 12;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int PERCENT = 34;
  public static final int NUMBER = 41;
  public static final int IDENT = 42;
  public static final int BREAK = 20;
  public static final int VOID = 16;
  public static final int COLON = 17;
  public static final int UNION = 10;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int READ = 23;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int GREATER_THAN_OR_EQUAL = 38;
  public static final int FORWARD_SLASH = 33;
  public static final int LESS_THAN = 39;
  public static final int PRINT = 24;
}

